apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j8fg9hjyk-python 
  janus-idp.io/tekton: j8fg9hjyk-python
  backstage.io/kubernetes-id: j8fg9hjyk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j8fg9hjyk-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  